# https://taskfile.dev

version: "3"

vars:
  PROJECT: ontv-kodi
  PLUGIN: plugin.video.ontv
  ADDONS_DIR: "/Volumes/Devo/Users/jago/Library/Application Support/Kodi/addons"
  REMOTE: pi4

tasks:
  test:
    cmds:
      - rm -rf "{{.ADDONS_DIR}}/{{.PLUGIN}}"
      - cp -R "{{.PLUGIN}}" "{{.ADDONS_DIR}}"
    silent: true

  package:
    desc: package and copy
    cmds:
      - zip -r {{.PLUGIN}}-`xmllint --xpath "string(//addon/@version)" {{.PLUGIN}}/addon.xml`.zip {{.PLUGIN}}
      - scp {{.PLUGIN}}-`xmllint --xpath "string(//addon/@version)" {{.PLUGIN}}/addon.xml`.zip pi4:~

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push || true

  export:
    desc: export env
    cmds:
      - mamba env export --no-builds  -n {{.PROJECT}} > environment.yml
